// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PosApp.Data;

#nullable disable

namespace PosApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241224154942_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("PosApp.Models.Product", b =>
                {
                    b.Property<string>("Sku")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Sku");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("PosApp.Models.Stock", b =>
                {
                    b.Property<string>("Sku")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Sku");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("PosApp.Models.Stock", b =>
                {
                    b.HasOne("PosApp.Models.Product", "Product")
                        .WithOne()
                        .HasForeignKey("PosApp.Models.Stock", "Sku")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
